DROP TABLE IF EXISTS FuelLog CASCADE;
DROP TABLE IF EXISTS Inspection CASCADE;
DROP TABLE IF EXISTS Maintenance CASCADE;
DROP TABLE IF EXISTS BusOperation CASCADE;
DROP TABLE IF EXISTS Insurance CASCADE;
DROP TABLE IF EXISTS Bus CASCADE;